---
title: "STOR 455 Class 14 R Notebook"
output: 
  pdf_document
---


```{r message=FALSE, warning=FALSE}
library(readr)

Exams4 <- read_csv("https://raw.githubusercontent.com/JA-McLean/STOR455/master/data/Exams4.csv")
```

```{r}
Exams4

means = tapply(Exams4$Grade, Exams4$Exam, mean)

tapply(Exams4$Grade, Exams4$Exam, mean)
tapply(Exams4$Grade, Exams4$Exam, sd)
tapply(Exams4$Grade, Exams4$Exam, length)

boxplot(Grade ~ Exam, data = Exams4)
points(means, col="red", pch=4)
```

```{r}
plot(Grade ~ Exam, data = Exams4)
points(means, col="red", pch=4)
abline(h = mean(Exams4$Grade), col = "blue")
```

```{r}
amodG=aov(Grade~factor(Exam),data=Exams4)
summary(amodG)
```

```{r}
plot(amodG)
round(tapply(Exams4$Grade,Exams4$Exam,sd),2)
```

```{r}
plot(amodG)
round(tapply(Exams4$Grade, Exams4$Exam, sd),2)
```

```{r}
modS=aov(Grade~factor(Student),data=Exams4)
summary(modS)

plot(modS, 1:2)
round(tapply(Exams4$Grade,Exams4$Student,sd),2)
```

```{r}
1 - (1 - 0.05)^10

1 - (1 - 0.05)^100
```

```{r}
t_LSD = qt(1 - 0.05/2, modS$df.residual)

MSE = summary(modS)[[1]][,3][2]

LSD = t_LSD * sqrt(MSE)*sqrt(1/4 + 1/4)
LSD
```
```{r}
1 - (1 - 0.05/10)^10

1 - (1 - 0.05/100)^100
```

```{r}
t_bf = qt(1 - 0.05/10/2, modS$df.residual)

BSD = t_bf * sqrt(MSE)*sqrt(1/4 + 1/4)
BSD
```

```{r}
HSD = qtukey(1-0.05, 5, modS$df.residual)/sqrt(2) * sqrt(MSE)*sqrt(1/4 + 1/4)
HSD
```

```{r}
pairwise.t.test(Exams4$Grade, Exams4$Student, p.adj = 'none')
```

```{r}
pairwise.t.test(Exams4$Grade, Exams4$Student, p.adj = 'bonf')
```

```{r}
TukeyHSD(modS) 
```

```{r warning=FALSE}
origpar = par()
par(mar=c(4,7,3,1))
hsd = TukeyHSD(modS)
plot(hsd, las=2)
par(origpar)
```
