---
title: "Lab 12: Work on Final Project"
author: "Zeyan Huang"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=F)
options(scipen=999)
library(tidyverse)
```

# Introduction

In this lab, you will work on the final paper with your groups. As you are doing the work with your groups, take notes so you can provide answers to the following questions. Each group member will have to complete one of these forms.

## Q1 (4 Points)

**What individual contributions have you made to the group project?**

I finished all the code for those two questions in the result part and analyzed the data and plot we got.

## Q2 (4 Points)

**What was the most difficult aspect of the group project?**

The most difficult part is choosing the variables we need from 85 columns, and fitting them into the glm() model. After we have those models we want, we need to do the model selection by hand which requires a lot of work and takes much time to analyze the summary of those models

## Q3 (2 Points)

**What suggestions do you have to make the group project better for the future?**

I think our project should include some machine learning parts to improve our model selection. A better model would be more accurate in predicting patients' survival probability in the ICU. And base on our goal difference, we should have different models for predicting survival probability for patients with various diseases.

